services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - frontend
      - backend
    environment:
      DB_SERVER: db
      DB_USER: root
      DB_PASS: 123456
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
      
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080
    networks:
      - backend

volumes:
  wordpress:
  db:

networks:
  frontend:
  backend: