name: CI/CD

on:
  push:
    branches: 
      - main

jobs:
  release:
    name: Compile, test and build
    runs-on: ubuntu-latest
        
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'

      - name: Compile
        run: ./grailsw compile

      - name: Run tests
        run: ./grailsw test-app

      - name: Build
        run: ./grailsw prod war