global:
  resolve_timeout: 1m
  # mail config
  # host: 'smtp.gmail.com:465'
  # auth_username: 'your_mail@gmail.com'
  # auth_password: ""
  # from: 'your_mail@gmail.com'
  # slack config
  # slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_by: [ alertname ]
  receiver: 'mail'
  repeat_interval: 5m
  routes:
    - receiver: 'mail'
      repeat_interval: 5m
      matchers:
        - severity="low"

    # - receiver: 'slack-devops'
    #   repeat_interval: 5m
    #   matchers:
    #     - severity="high"

receivers:
  - name: 'mail'
    # email_configs:
    #   to: 'some_mail@gmail.com'

  # - name: 'slack-devops'
  #   slack_configs:
  #   - channel: '#test'
  #     send_resolved: true
  #     icon_url: https://avatars3.githubusercontent.com/u/3380462
  #     title: |-
  #       [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
  #       {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
  #         {{" "}}(
  #         {{- with .CommonLabels.Remove .GroupLabels.Names }}
  #           {{- range $index, $label := .SortedPairs -}}
  #             {{ if $index }}, {{ end }}
  #             {{- $label.Name }}="{{ $label.Value -}}"
  #           {{- end }}
  #         {{- end -}}
  #         )
  #       {{- end }}
  #       text: >-
  #       {{ range .Alerts -}}
  #       *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

  #       *Description:* {{ .Annotations.description }}

  #       *Details:*
  #         {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
  #         {{ end }}
  #       {{ end }}
         
