groups:
- name: hosts
  rules:
  # Alert for any instance that is unreachable for >5 minutes.
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels: # labels and annotations are new
      severity: hight
      team: devops
    annotations:
      summary: 'Alert with hight severity.'

  - alert: HighLoad
    expr: node_load1 > 0.5
    for: 2m
    labels:
      severity: hight
      team: devops
    annotations:
      summary: "Instance {{ $labels.instance }} under high load"
      description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."